# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43682ba3faba9b922dd9bfdb68738889a84fda252c0b84272c990d9a553434c620fba3aadacf13c58a25d9601fe59510667b5c32979732b12f0fb5178572256b

test:
  secret_key_base: ff8b718aae11903d4c410a03e5c9ffed417b37ee389e441a436f00c56669fc7773175b458c92e30a16cb1d05a6071de0017ed8bef785fe80a42a31047fca55fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
